#import <Foundation/Foundation.h>
#import <AFNetworking/AFURLResponseSerialization.h>

/**
* Backhand Api
* Apis to access Backhand backend services
*
* OpenAPI spec version: 0.0.1
* Contact: sanket@blackcurrantapps.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


@interface SWGJSONResponseSerializer : AFJSONResponseSerializer

@end
