#import <Foundation/Foundation.h>
#import "SWGChallenge.h"
#import "SWGClub.h"
#import "SWGClubParticipants.h"
#import "SWGEvent.h"
#import "SWGGame.h"
#import "SWGScoreboard.h"
#import "SWGUser.h"
#import "SWGApi.h"

/**
* Backhand Api
* Apis to access Backhand backend services
*
* OpenAPI spec version: 0.0.1
* Contact: sanket@blackcurrantapps.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGUserApi: NSObject <SWGApi>

extern NSString* kSWGUserApiErrorDomain;
extern NSInteger kSWGUserApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// Add sport to user profile
///
/// @param sport Sport Enum
/// @param skillLevel 
/// @param favouritePlayer 
/// @param playingSince 
///  code:200 message:"Updated Profile"
/// @return SWGUser*
-(NSNumber*) addSportPostWithSport: (NSString*) sport
    skillLevel: (NSNumber*) skillLevel
    favouritePlayer: (NSString*) favouritePlayer
    playingSince: (NSNumber*) playingSince
    completionHandler: (void (^)(SWGUser* output, NSError* error)) handler;

/// Delete sport to user profile
///
/// @param sport Sport Enum
///  code:200 message:"Updated Profile"
/// @return SWGUser*
-(NSNumber*) deleteSportPostWithSport: (NSString*) sport
    completionHandler: (void (^)(SWGUser* output, NSError* error)) handler;

/// Get challenge recommendations
///
/// @param sport Sport Enum (optional)
/// @param limit Limit the number of results (optional) (default to 50)
///  code:200 message:"List of Users"
/// @return NSArray<SWGUser>*
-(NSNumber*) getChallengeRecommendationsGetWithSport: (NSString*) sport
    limit: (NSNumber*) limit
    completionHandler: (void (^)(NSArray<SWGUser>* output, NSError* error)) handler;

/// Get List of Clubs
/// Get list of clubs for user's city
///
/// @param city City (optional)
/// @param locality City (optional)
/// @param sport Sport Enum (optional)
/// @param limit Limit the number of results (optional) (default to 50)
///  code:200 message:"List of Clubs"
/// @return NSArray<SWGClub>*
-(NSNumber*) getClubsGetWithCity: (NSString*) city
    locality: (NSString*) locality
    sport: (NSString*) sport
    limit: (NSNumber*) limit
    completionHandler: (void (^)(NSArray<SWGClub>* output, NSError* error)) handler;

/// Get Club Participants
/// Get the players for various sports within a club
///
/// @param clubId City
/// @param limit Limit the number of results (optional) (default to 50)
///  code:200 message:"Club Details"
/// @return SWGClubParticipants*
-(NSNumber*) getClubsParticipantsGetWithClubId: (NSNumber*) clubId
    limit: (NSNumber*) limit
    completionHandler: (void (^)(SWGClubParticipants* output, NSError* error)) handler;

/// Get List of Events
/// Get list of events for a city
///
/// @param city City
///  code:200 message:"List of Events"
/// @return NSArray<SWGEvent>*
-(NSNumber*) getEventsGetWithCity: (NSString*) city
    completionHandler: (void (^)(NSArray<SWGEvent>* output, NSError* error)) handler;

/// Get Players List to load in add sport screen
///
/// @param sport Sport Enum
///  code:200 message:"Player List"
/// @return NSArray<NSString*>*
-(NSNumber*) getFeaturedPlayersPostWithSport: (NSString*) sport
    completionHandler: (void (^)(NSArray<NSString*>* output, NSError* error)) handler;

/// Get challenges
/// A list of challenges
///
/// @param limit Limit the number of results (optional) (default to 50)
///  code:200 message:"List of Challenges"
/// @return NSArray<SWGChallenge>*
-(NSNumber*) getMyChallengesGetWithLimit: (NSNumber*) limit
    completionHandler: (void (^)(NSArray<SWGChallenge>* output, NSError* error)) handler;

/// Get Scoreboard for a sport
/// A list of games that are validated by the opoonent.
///
/// @param sport Sport Enum
/// @param limit Limit the number of results (optional) (default to 50)
///  code:200 message:"Scoreboard per sport"
/// @return SWGScoreboard*
-(NSNumber*) getScoreboardGetWithSport: (NSString*) sport
    limit: (NSNumber*) limit
    completionHandler: (void (^)(SWGScoreboard* output, NSError* error)) handler;

/// Get Authenticated user's profile
///
///  code:200 message:"User's own profile"
/// @return SWGUser*
-(NSNumber*) getSelfProfileGetWithCompletionHandler: 
    (void (^)(SWGUser* output, NSError* error)) handler;

/// Get user profile
///
/// @param userId 
///  code:200 message:"User profile"
/// @return SWGUser*
-(NSNumber*) getUserPostWithUserId: (NSNumber*) userId
    completionHandler: (void (^)(SWGUser* output, NSError* error)) handler;

/// Challenge someone for a game
/// Create a new challenge and send a push notification to opponents.
///
/// @param gameSport 
/// @param gameType 
/// @param gameChallengerPlayer1 
/// @param gameOppositionPlayer1 
/// @param gameChallengerPlayer2  (optional)
/// @param gameOppositionPlayer2  (optional)
///  code:200 message:"Challenge Created"
/// @return SWGChallenge*
-(NSNumber*) newChallengePostWithGameSport: (NSString*) gameSport
    gameType: (NSString*) gameType
    gameChallengerPlayer1: (NSNumber*) gameChallengerPlayer1
    gameOppositionPlayer1: (NSNumber*) gameOppositionPlayer1
    gameChallengerPlayer2: (NSNumber*) gameChallengerPlayer2
    gameOppositionPlayer2: (NSNumber*) gameOppositionPlayer2
    completionHandler: (void (^)(SWGChallenge* output, NSError* error)) handler;

/// Make a new game
/// Create a new game and send a push notification to opponents to verify the same.
///
/// @param gameSport 
/// @param gameType 
/// @param gameChallengerScore 
/// @param gameOppositionScore 
/// @param gameChallengerPlayer1 
/// @param gameOppositionPlayer1 
/// @param gameScoreFormat  (optional)
/// @param gameChallengerPlayer2  (optional)
/// @param gameOppositionPlayer2  (optional)
///  code:200 message:"Game Created"
/// @return SWGGame*
-(NSNumber*) newGamePostWithGameSport: (NSString*) gameSport
    gameType: (NSString*) gameType
    gameChallengerScore: (NSNumber*) gameChallengerScore
    gameOppositionScore: (NSNumber*) gameOppositionScore
    gameChallengerPlayer1: (NSNumber*) gameChallengerPlayer1
    gameOppositionPlayer1: (NSNumber*) gameOppositionPlayer1
    gameScoreFormat: (NSString*) gameScoreFormat
    gameChallengerPlayer2: (NSNumber*) gameChallengerPlayer2
    gameOppositionPlayer2: (NSNumber*) gameOppositionPlayer2
    completionHandler: (void (^)(SWGGame* output, NSError* error)) handler;

/// Push Notify User
///
/// @param userId 
/// @param message 
///  code:200 message:"Notification Sent"
-(NSNumber*) notifyNewMessagePostWithUserId: (NSNumber*) userId
    message: (NSString*) message
    completionHandler: (void (^)(NSError* error)) handler;

/// Query Users
/// search users based on name / phone number / email / name / club
///
/// @param query 
/// @param cityFilter filter by club_id (optional)
/// @param clubFilter filter by club_id (optional)
/// @param limit Limit the number of results (optional) (default to 50)
///  code:200 message:"List of Users"
/// @return NSArray<SWGUser>*
-(NSNumber*) searchUsersPostWithQuery: (NSString*) query
    cityFilter: (NSString*) cityFilter
    clubFilter: (NSNumber*) clubFilter
    limit: (NSNumber*) limit
    completionHandler: (void (^)(NSArray<SWGUser>* output, NSError* error)) handler;

/// Update favourite player
///
/// @param sport Sport Enum
/// @param player New Status Message
///  code:200 message:"Favourite Player Updated"
-(NSNumber*) updateFavouritePlayerPostWithSport: (NSString*) sport
    player: (NSString*) player
    completionHandler: (void (^)(NSError* error)) handler;

/// Update profile picture
/// Upload a picture and get a url to the picture
///
/// @param file File to upload Accepted formats jpg,jpeg,png
///  code:200 message:"URL of the picture"
-(NSNumber*) updateProfilePicturePostWithFile: (NSURL*) file
    completionHandler: (void (^)(NSError* error)) handler;

/// Update Profile
/// If the profilePic file is provided, we save it and update the profile pic link in the user profile. Also, all other provided fileds are updated.
///
/// @param mobileNumber 
/// @param birthDate format - DD/MM/YYYY
/// @param handedness 
/// @param city 
/// @param clubIds 
///  code:200 message:"Updated Profile"
/// @return SWGUser*
-(NSNumber*) updateProfilePostWithMobileNumber: (NSString*) mobileNumber
    birthDate: (NSString*) birthDate
    handedness: (NSString*) handedness
    city: (NSString*) city
    clubIds: (NSArray<NSNumber*>*) clubIds
    completionHandler: (void (^)(SWGUser* output, NSError* error)) handler;

/// Update profile picture
/// Upload a picture and get a url to the picture
///
/// @param message New Status Message
///  code:200 message:"Status Updated"
-(NSNumber*) updateStatusMessagePostWithMessage: (NSString*) message
    completionHandler: (void (^)(NSError* error)) handler;

/// Verify the score
/// Validate the score entered by an opponent.
///
/// @param gameId 
///  code:200 message:"Game Verified"
/// @return SWGGame*
-(NSNumber*) verifyGamePostWithGameId: (NSNumber*) gameId
    completionHandler: (void (^)(SWGGame* output, NSError* error)) handler;


@end
