#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Backhand Api
* Apis to access Backhand backend services
*
* OpenAPI spec version: 0.0.1
* Contact: sanket@blackcurrantapps.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGAuthSuccess
@end

@interface SWGAuthSuccess : SWGObject


@property(nonatomic) NSString* tokenType;

@property(nonatomic) NSNumber* expiresIn;

@property(nonatomic) NSString* accessToken;

@property(nonatomic) NSString* refreshToken;

@end
