#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Backhand Api
* Apis to access Backhand backend services
*
* OpenAPI spec version: 0.0.1
* Contact: sanket@blackcurrantapps.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGUserShortProfile.h"


@protocol SWGChallenge
@end

@interface SWGChallenge : SWGObject


@property(nonatomic) NSNumber* challengeId;
/* Timestamp of the challenge [optional]
 */
@property(nonatomic) NSString* challengeTs;

@property(nonatomic) NSString* challengeUpdatedTs;

@property(nonatomic) NSString* challengeSport;

@property(nonatomic) NSString* challengeType;

@property(nonatomic) NSNumber* challengeChallengerPlayer1;

@property(nonatomic) NSNumber* challengeChallengerPlayer2;

@property(nonatomic) NSNumber* challengeOppositionPlayer1;

@property(nonatomic) NSNumber* challengeOppositionPlayer2;

@property(nonatomic) NSNumber* challengeClubId;

@property(nonatomic) SWGUserShortProfile* challengeChallengerPlayer1Profile;

@property(nonatomic) SWGUserShortProfile* challengeChallengerPlayer2Profile;

@property(nonatomic) SWGUserShortProfile* challengeOppositionPlayer1Profile;

@property(nonatomic) SWGUserShortProfile* challengeOppositionPlayer2Profile;

@end
