#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Backhand Api
* Apis to access Backhand backend services
*
* OpenAPI spec version: 0.0.1
* Contact: sanket@blackcurrantapps.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGClub.h"


@protocol SWGEvent
@end

@interface SWGEvent : SWGObject


@property(nonatomic) NSNumber* eventId;

@property(nonatomic) NSString* eventName;

@property(nonatomic) NSString* eventDescription;

@property(nonatomic) NSString* eventCity;

@property(nonatomic) NSString* eventSport;

@property(nonatomic) NSString* eventStartDate;

@property(nonatomic) NSString* eventEndDate;

@property(nonatomic) NSString* eventBackgroundPicture;

@property(nonatomic) NSNumber* eventLat;

@property(nonatomic) NSNumber* eventLon;

@property(nonatomic) SWGClub* eventClub;

@end
