#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Backhand Api
* Apis to access Backhand backend services
*
* OpenAPI spec version: 0.0.1
* Contact: sanket@blackcurrantapps.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGFeaturedPlayer
@end

@interface SWGFeaturedPlayer : SWGObject


@property(nonatomic) NSNumber* playerId;

@property(nonatomic) NSString* playerName;

@property(nonatomic) NSString* playerWikipediaUrl;

@property(nonatomic) NSString* playerSport;

@property(nonatomic) NSString* playerProfilePicUrl;

@property(nonatomic) NSString* playerHomeCountry;

@property(nonatomic) NSString* playerHandedness;

@property(nonatomic) NSNumber* playerTitlesWon;

@property(nonatomic) NSNumber* playerPlayingSince;

@property(nonatomic) NSNumber* playerTotalMatches;

@property(nonatomic) NSNumber* playerWinRate;

@property(nonatomic) NSString* playerBrief;

@end
