#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Backhand Api
* Apis to access Backhand backend services
*
* OpenAPI spec version: 0.0.1
* Contact: sanket@blackcurrantapps.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGGame.h"


@protocol SWGInlineResponse200
@end

@interface SWGInlineResponse200 : SWGObject


@property(nonatomic) NSNumber* pendingScores;

@property(nonatomic) NSNumber* totalMatches;

@property(nonatomic) NSNumber* winRate;

@property(nonatomic) NSArray<SWGGame>* matches;

@end
