#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Backhand Api
* Apis to access Backhand backend services
*
* OpenAPI spec version: 0.0.1
* Contact: sanket@blackcurrantapps.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGNews
@end

@interface SWGNews : SWGObject


@property(nonatomic) NSNumber* varNewsId;

@property(nonatomic) NSString* varNewsTitle;

@property(nonatomic) NSString* varNewsContent;

@property(nonatomic) NSString* varNewsAuthor;

@property(nonatomic) NSString* varNewsSport;

@property(nonatomic) NSString* varNewsPublishTs;

@property(nonatomic) NSString* varNewsImageUrl;

@end
