#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Backhand Api
* Apis to access Backhand backend services
*
* OpenAPI spec version: 0.0.1
* Contact: sanket@blackcurrantapps.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGUserShortProfile
@end

@interface SWGUserShortProfile : SWGObject


@property(nonatomic) NSNumber* userId;

@property(nonatomic) NSString* userFirstName;

@property(nonatomic) NSString* userLastName;

@property(nonatomic) NSString* email;

@property(nonatomic) NSString* userMobileNo;

@property(nonatomic) NSString* userProfilePicUrl;

@property(nonatomic) NSString* userGender;

@property(nonatomic) NSNumber* userIsReal;

@end
