#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Backhand Api
* Apis to access Backhand backend services
*
* OpenAPI spec version: 0.0.1
* Contact: sanket@blackcurrantapps.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGUserUserClubs.h"


@protocol SWGUser
@end

@interface SWGUser : SWGObject


@property(nonatomic) NSNumber* userId;

@property(nonatomic) NSString* userFirstName;

@property(nonatomic) NSString* userLastName;

@property(nonatomic) NSNumber* userAge;

@property(nonatomic) NSString* email;

@property(nonatomic) NSString* userMobileNo;

@property(nonatomic) NSString* userProfilePicUrl;

@property(nonatomic) NSString* userSocialId;

@property(nonatomic) NSString* userHandedness;

@property(nonatomic) NSString* userGender;
/* example - Mumbai [optional]
 */
@property(nonatomic) NSString* userCity;
/* example - Borivali [optional]
 */
@property(nonatomic) NSString* userLocality;

@property(nonatomic) NSNumber* userPlaysBadminton;

@property(nonatomic) NSNumber* userPlaysTennis;

@property(nonatomic) NSNumber* userPlaysSquash;

@property(nonatomic) NSNumber* userSkillLevelBadminton;

@property(nonatomic) NSNumber* userSkillLevelTennis;

@property(nonatomic) NSNumber* userSkillLevelSquash;

@property(nonatomic) NSNumber* userPlayingBadmintonSince;

@property(nonatomic) NSNumber* userPlayingTennisSince;

@property(nonatomic) NSNumber* userPlayingSquashSince;

@property(nonatomic) NSString* userBadmintonFavouritePlayer;

@property(nonatomic) NSString* userTennisFavouritePlayer;

@property(nonatomic) NSString* userSquashFavouritePlayer;

@property(nonatomic) NSNumber* userIsReal;

@property(nonatomic) NSNumber* userLevel;
/* DD/MM//YYYY [optional]
 */
@property(nonatomic) NSString* userBirthdate;

@property(nonatomic) NSArray<SWGUserUserClubs>* userClubs;

@property(nonatomic) NSString* userStatusMessage;

@end
